# Generated by Django 4.0.6 on 2022-10-01 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parentchild', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parentchild.parent')),
            ],
        ),
    ]
