# Generated by Django 4.0.6 on 2022-10-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parentchild', '0003_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parentchild.child')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parentchild.classes')),
            ],
        ),
    ]
